### PR TITLE
colors and refresh information

### PR DESCRIPTION
**Pull request by SegFault42**
- Refactoring main.c 
- Color for better readability
- Auto refresh

### CODE REVIEW

**Comment by joel16** [comment]
I'd like to merge this, but that indentation (IMO) is horrible lol.
I know my indentation looked pretty crappy on github, but that's because Notepad++ messes with the formatting sometimes. It looks well indentened on my notepad, but doesn't when I push it to git.

If you can revert to my indentation:
const char  *getModel() -> const char \* getModel()
and not mess with the colors or the title aligment I'd be happy to merge.

Thank you for fixing certain indentation issues though. I blame notepad++ for that. Might come off as an asshole asking you to fix these, but it's because I'm trying to retain the same style the original PSPident and PS2ident uses.

**Comment by joel16** [comment]
On a second thought, I might keep the colors because it goes easy on the eyes and makes things more readable, however if you can change the other things I requested I'll gladly merge this.

**Comment by SegFault42** [comment]
ok, you want to keep the title alignement ? And what can i do for the variable indentation and declaration ?

**Comment by joel16** [comment]
Well function declarations should be just one space: 
for example you have
`int    vaPrint(char *format, ...)`
but what I mean is like `int vaPrint(char *format, ...)` (just one space after the function type.) Also I use 'char \* str' and not 'char *str'. It's kind of like an ocd thing for me.

also this bit

```
if (region < 7)
        return regions[region];
    else
        return regions[7];
```

Just a new line and one tab should be fine for indentation there.

local variables inside functions need to be indented properly as well.
For example `u8     screens = 0;` should be `u8 screens = 0;` one space.
Just do as much as you can, I'll fix the rest later :p  

And yes, I'd like it if you reverted the centered alignment back to left align for the title and the "press to exit" string.

Thanks for understanding!

**Comment by SegFault42** [comment]
i think it's good right now. Sorry for my indentation ^^.

**Comment by joel16** [comment]
No problem, looks good. I'll merge.

**Comment by SegFault42** [comment]
thank you

**Pull request merged**
